# Tensors

In [2]:
import torch
import numpy as np

C:\Users\Luigi\Anaconda3\envs\wekeo\lib\site-packages\tqdm\auto.py:22: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


## Tensors initialization
Like with NumPy, a tensor can be initialized with a list of numbers

In [2]:
data = [[1, 2],[3, 4]]
x_data = torch.tensor(data)
x_data

tensor([[1, 2],
        [3, 4]])

In [4]:
np_array = np.array(data)
x_np = torch.from_numpy(np_array)
x_np

tensor([[1, 2],
        [3, 4]], dtype=torch.int32)

Tensors already filled with values such as ones, zeros or random numbers can be created with the same shape of another tensor

In [7]:
rand_tensor = torch.rand(x_data.shape, dtype=torch.float) # overrides the datatype of x_data
print(f"Random Tensor: \n {rand_tensor} \n")

Random Tensor: 
 tensor([[0.6501, 0.2127],
        [0.4781, 0.4237]]) 



In [8]:
print(f"Shape of tensor: {rand_tensor.shape}")
print(f"Datatype of tensor: {rand_tensor.dtype}")
print(f"Device tensor is stored on: {rand_tensor.device}")

Shape of tensor: torch.Size([2, 2])
Datatype of tensor: torch.float32
Device tensor is stored on: cpu


## Operation on tensors
A tensor is a multi-dimensional data structure that supports many operations from linear algebra, matric manipulation and others. A tensor can work on a cpu or on a gpu. If a gpu is available the tensor API provides a metod to move a tensor from the cpu to the gpu.

In [10]:
if torch.cuda.is_available():
    tensor = tensor.to("cuda")

### Slicing

In [13]:
data = [[1, 2, 3],[4, 5, 6], [7, 8, 9]]
tensor = torch.tensor(data)
print(f"First row: {tensor[0]}")
print(f"First column: {tensor[:, 0]}")
print(f"Last column: {tensor[..., -1]}")
tensor[:, 0] = 0
print(tensor)

First row: tensor([1, 2, 3])
First column: tensor([1, 4, 7])
Last column: tensor([3, 6, 9])
tensor([[0, 2, 3],
        [0, 5, 6],
        [0, 8, 9]])


### Concatenation

In [14]:
t1 = torch.cat([tensor, tensor, tensor], dim=1)
print(t1)

tensor([[0, 2, 3, 0, 2, 3, 0, 2, 3],
        [0, 5, 6, 0, 5, 6, 0, 5, 6],
        [0, 8, 9, 0, 8, 9, 0, 8, 9]])


In [17]:
t1.shape

torch.Size([3, 9])

### Stacking

In [15]:
t2 = torch.stack([tensor, tensor, tensor], dim=1)
print(t2)

tensor([[[0, 2, 3],
         [0, 2, 3],
         [0, 2, 3]],

        [[0, 5, 6],
         [0, 5, 6],
         [0, 5, 6]],

        [[0, 8, 9],
         [0, 8, 9],
         [0, 8, 9]]])


In [16]:
t2.shape

torch.Size([3, 3, 3])

### Matrix multiplication
In order to perform a matrix multiplication of two matrices A and B, the number of colums of the firts matrix must be equal to the number of rows of the second matrix. 

In [22]:
data = [[1, 2, 3],[0, 5, 6], [0, 0, 9]]
A = torch.tensor(data)
x = torch.tensor([1, -1, 2])
A @ x

tensor([ 5,  7, 18])

### Element-wise product

In [24]:
z1 = tensor * tensor
z2 = tensor.mul(tensor)
z1, z2

(tensor([[ 1,  4,  9],
         [ 0, 25, 36],
         [ 0,  0, 81]]),
 tensor([[ 1,  4,  9],
         [ 0, 25, 36],
         [ 0,  0, 81]]))

### In-place operations

In [25]:
print(f"{tensor} \n")
tensor.add_(5)
print(tensor)

tensor([[1, 2, 3],
        [0, 5, 6],
        [0, 0, 9]]) 

tensor([[ 6,  7,  8],
        [ 5, 10, 11],
        [ 5,  5, 14]])
