## PyTorch tensor
---
In this notebook we will learn some of the methods available on a tensor object.


In [ ]:
import torch
a = torch.ones(3)
a

tensor([1., 1., 1.])

An image can be represented as a 3 dimensional array [channels, rows, columns].

In [ ]:
img_t = torch.randn(3, 5, 5) # shape [channels, rows, columns]
img_t

tensor([[[ 0.2610, -0.7911,  0.5575,  0.3069, -1.4433],
         [ 1.5622,  0.3699,  0.7384,  1.3187, -0.3897],
         [-0.5342, -0.2891,  0.5901, -1.4438, -1.6414],
         [ 0.1158,  0.9506, -0.7869,  1.1564,  0.7902],
         [-0.7936,  0.3055, -0.3932, -0.6455,  1.9615]],

        [[-0.0884, -1.0892,  0.6155, -0.0950,  1.5019],
         [-0.0341, -0.6863, -0.7033,  0.6989,  0.4996],
         [-0.4508,  0.9287, -0.6297, -0.1203,  1.7448],
         [ 0.0107,  0.1420, -2.0567, -0.5690,  0.0077],
         [-1.7630, -0.3729,  0.5218, -1.6114,  0.7342]],

        [[-1.0558,  1.2811, -0.0932, -1.9150, -1.3845],
         [ 1.7504,  1.8145, -1.0842,  0.1109,  3.1704],
         [ 0.4941,  0.0851, -0.9222,  0.1480,  1.1355],
         [-0.4941, -1.0956,  0.3403,  2.5229,  1.0648],
         [ 0.7337,  0.2495,  0.6792, -1.2740, -0.9321]]])

In [ ]:
img_t.shape

torch.Size([3, 5, 5])

A batch of images is a 4D array that can contain one or more images [batch, channels, rows, columns]

In [ ]:
batch_t = torch.randn(2, 3, 5, 5) # shape [batch, channels, rows, columns]
batch_t

tensor([[[[ 0.9923,  2.0979, -0.9044,  1.6845, -1.6281],
          [-0.5906,  1.0107,  0.5731, -0.3924, -0.9911],
          [ 0.0274, -0.3743,  0.2194,  0.9597, -1.5001],
          [-3.5758,  0.5653,  0.0742,  0.0120,  0.6224],
          [ 0.3064,  0.5683, -0.1840,  0.0158,  0.9675]],

         [[ 0.6663, -0.9410,  0.4565,  0.0111, -0.2275],
          [-0.3156, -0.5872, -0.0995,  0.1455, -0.4873],
          [-1.3322,  0.5824,  0.3241, -1.1951,  0.4731],
          [ 0.8790,  0.0985,  0.0183, -0.1201,  0.1062],
          [-0.0165,  0.2755, -1.3555,  0.5205,  0.5806]],

         [[ 0.4857,  1.1666,  0.5062,  1.5914,  0.3188],
          [ 0.0577,  1.5179,  0.1602, -0.7869,  1.2026],
          [ 0.2737, -1.2003, -0.1132, -0.3264,  0.6059],
          [-0.5263, -0.2398, -1.3702, -1.2158, -0.7375],
          [ 0.3911,  0.5220, -0.2402,  0.6844,  1.7875]]],


        [[[-0.1090, -0.1774,  0.6930, -0.2975, -0.4742],
          [ 1.1265, -0.5921,  1.1657, -1.5748,  1.0634],
          [ 0.6736,  0.

In [ ]:
batch_t.shape

torch.Size([2, 3, 5, 5])

In [ ]:
weights = torch.tensor([0.2126, 0.7152, 0.0722])
weights

tensor([0.2126, 0.7152, 0.0722])

In [ ]:
weights.shape

torch.Size([3])

In [ ]:
unsqueezed_weights = weights.unsqueeze(-1).unsqueeze(-1)
unsqueezed_weights

tensor([[[0.2126]],

        [[0.7152]],

        [[0.0722]]])

In [ ]:
unsqueezed_weights.shape

torch.Size([3, 1, 1])

In [ ]:
img_weights = img_t * unsqueezed_weights # (3, 5, 5) x (3, 1, 1)
img_weights

tensor([[[ 0.0555, -0.1682,  0.1185,  0.0652, -0.3068],
         [ 0.3321,  0.0786,  0.1570,  0.2804, -0.0829],
         [-0.1136, -0.0615,  0.1254, -0.3070, -0.3490],
         [ 0.0246,  0.2021, -0.1673,  0.2458,  0.1680],
         [-0.1687,  0.0649, -0.0836, -0.1372,  0.4170]],

        [[-0.0632, -0.7790,  0.4402, -0.0680,  1.0742],
         [-0.0244, -0.4909, -0.5030,  0.4998,  0.3573],
         [-0.3224,  0.6642, -0.4503, -0.0861,  1.2479],
         [ 0.0076,  0.1016, -1.4709, -0.4070,  0.0055],
         [-1.2609, -0.2667,  0.3732, -1.1525,  0.5251]],

        [[-0.0762,  0.0925, -0.0067, -0.1383, -0.1000],
         [ 0.1264,  0.1310, -0.0783,  0.0080,  0.2289],
         [ 0.0357,  0.0061, -0.0666,  0.0107,  0.0820],
         [-0.0357, -0.0791,  0.0246,  0.1822,  0.0769],
         [ 0.0530,  0.0180,  0.0490, -0.0920, -0.0673]]])

In [ ]:
img_weights.shape

torch.Size([3, 5, 5])

In [ ]:
batch_weights = batch_t * unsqueezed_weights # (2, 3, 5, 5) x (3, 1, 1)
batch_weights

tensor([[[[ 2.1095e-01,  4.4601e-01, -1.9228e-01,  3.5813e-01, -3.4614e-01],
          [-1.2557e-01,  2.1486e-01,  1.2183e-01, -8.3428e-02, -2.1070e-01],
          [ 5.8204e-03, -7.9577e-02,  4.6641e-02,  2.0403e-01, -3.1893e-01],
          [-7.6021e-01,  1.2018e-01,  1.5769e-02,  2.5608e-03,  1.3232e-01],
          [ 6.5135e-02,  1.2082e-01, -3.9111e-02,  3.3486e-03,  2.0569e-01]],

         [[ 4.7657e-01, -6.7299e-01,  3.2648e-01,  7.9134e-03, -1.6272e-01],
          [-2.2575e-01, -4.1997e-01, -7.1166e-02,  1.0409e-01, -3.4855e-01],
          [-9.5280e-01,  4.1655e-01,  2.3181e-01, -8.5473e-01,  3.3839e-01],
          [ 6.2867e-01,  7.0462e-02,  1.3102e-02, -8.5891e-02,  7.5957e-02],
          [-1.1816e-02,  1.9706e-01, -9.6948e-01,  3.7229e-01,  4.1526e-01]],

         [[ 3.5066e-02,  8.4230e-02,  3.6549e-02,  1.1490e-01,  2.3015e-02],
          [ 4.1658e-03,  1.0959e-01,  1.1566e-02, -5.6812e-02,  8.6831e-02],
          [ 1.9758e-02, -8.6664e-02, -8.1755e-03, -2.3568e-02,  4.3744e-

In [ ]:
batch_weights.shape

torch.Size([2, 3, 5, 5])

In [ ]:
batch_weights.dtype

torch.float32

In [ ]:
a = torch.ones(3, 2)
a_t = torch.transpose(a, 0, 1)  # 0 and 1 are the dimensions to be swapped
a_t.shape

torch.Size([2, 3])

In [ ]:
a = torch.zeros(3, 5)

In [ ]:
for i in range(0, 3):
  for j in range(0, 5):
    a[i, j] = i + j

In [ ]:
a

tensor([[0., 1., 2., 3., 4.],
        [1., 2., 3., 4., 5.],
        [2., 3., 4., 5., 6.]])

In [ ]:
a.transpose(0, 1)

tensor([[0., 1., 2.],
        [1., 2., 3.],
        [2., 3., 4.],
        [3., 4., 5.],
        [4., 5., 6.]])

We can access its elements by its indices

In [ ]:
float(a[1, 2])

3.0

A tensor occupies a contiguous one dimensional indexed  space of elements (integers, floats). This can be seen when we store the data onto the hard disk.

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])

In [ ]:
points_storage = points.storage()

In [ ]:
points_storage[5]

1.0

## Inplace methods
These are methods that are performed on the tensor's elements to update their values and do not return a new tensor. These methods' names are characterized by trailing undescore.

In [ ]:
points.zero_()

tensor([[0., 0.],
        [0., 0.],
        [0., 0.]])

## Tensor metadata: size, offset and stride
The size (shape) of a tensor indicates how many elements there are on each dimension.

In [ ]:
points = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]])
points.shape

torch.Size([3, 2])

The offset indicates the index of the 1st element of the tensor in the storage.

In [ ]:
offset = points.storage_offset()
offset

0

The stride is the number of elements that must be skipped to get to the next element of the next dimension. For example to get the next point of our list we have to skip two elements.

In [ ]:
stride = points.stride()
stride

(2, 1)

In [ ]:
points_storage = points.storage()

We can compute the storage index to access a tensor using its indices (row and column)

In [ ]:
i = 1
j = 1
storage_index = offset + stride[0] * i + stride[1] * j
storage_index

3

In [ ]:
points_storage[storage_index]

3.0

We can use a shortcut to compute the transpose of a tensor.

In [ ]:
points_t = points.t()
points_t

tensor([[4., 5., 2.],
        [1., 3., 1.]])

In [ ]:
points_t.is_contiguous()

False

## Moving tensors to the GPU
In Google Colab we need to chanage the runtime to use the GPU

In [ ]:
points_gpu = points.to(device='cuda')

In [ ]:
points_gpu * 2 # stored in the GPU

tensor([[ 8.,  2.],
        [10.,  6.],
        [ 4.,  2.]], device='cuda:0')

In [ ]:
points # stored in the CPU

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

## NumPy interoperability
We can copy a PyTorch tensor stored on CPU RAM into a NumPy array.

In [ ]:
points_np = points.numpy()
points_np

array([[4., 1.],
       [5., 3.],
       [2., 1.]], dtype=float32)

Conversely we can copy a NumPy array into a PyTorch tensor

In [ ]:
points_tensor = torch.from_numpy(points_np)
points_tensor

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

We write the tensor data into a file

In [ ]:
with open('/content/sample_data/ourpoints.t','wb') as f:
  torch.save(points, f)

We read the data from the file

In [ ]:
with open('/content/sample_data/ourpoints.t','rb') as f:
  points_copy = torch.load(f)
points_copy

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]])

In [ ]:
import h5py

We write the data in a different file format: hdf5

In [ ]:
f = h5py.File('/content/sample_data/ourpoints.hdf5', 'w')
dset = f.create_dataset('coords', data=points.numpy())
f.close()

We read a subset of the data

In [ ]:
f = h5py.File('/content/sample_data/ourpoints.hdf5', 'r')
dset = f['coords']
last_points = dset[-2:]
last_points

array([[5., 3.],
       [2., 1.]], dtype=float32)

We copy the data into a tensor

In [ ]:
last_points = torch.from_numpy(dset[-2:])
f.close()